### ISSUE TITLE
Flat volumetric interface (no internal tank) vs. regular volumetric interface (internal tank)

### ISSUE THREAD

**Issue by daddy77gaming** [exzhawk/VolumetricFlask#10]
version 0.16, used in FTB interactions 2.0 beta test server.

![image](https://user-images.githubusercontent.com/31905330/85637481-9c736280-b683-11ea-954c-e3ef821bac18.png)

flat interface without tank, fails recipes creating filled flasks.

![image](https://user-images.githubusercontent.com/31905330/85637531-be6ce500-b683-11ea-9829-24f7bf39d4bf.png)

regular volumetric interface with internal tank does work fine creating filled flasks.

Expected both to behave similar.

**Comment by exzhawk** [comment]
should be fixed in d9ad9161c97ac957f44aab4f54af798c43baafe1, released in version 0.17 on curseforge
