### ISSUE TITLE
Volumetric interface will only wrench north.

### ISSUE THREAD

**Issue by daddy77gaming** [exzhawk/VolumetricFlask#11]
version 0.16, used in FTB interactions 2.0 beta test server.

When trying to point an interface into something using a wrench the interface will only point north no other direction.

![image](https://user-images.githubusercontent.com/31905330/85951065-09774880-b961-11ea-8241-24ce9342bce1.png)

Would be nice to have it omnidirectional.

**Comment by exzhawk** [comment]
fixed in 5b3c52362dcd4ae13100affb220f8d4e4a8c3114, release in version 0.18 on curseforge
