### ISSUE TITLE
Volumetric flasks missing and changing NBT on craft and use.

### ISSUE THREAD

**Issue by daddy77gaming** [exzhawk/VolumetricFlask#12]
When crafted the volumetric flasks are like this:

![2020-06-28_23 59 06](https://user-images.githubusercontent.com/31905330/85960478-08b3d600-b9a4-11ea-9364-7ecb2b85cc8d.png)
which do not work in Filler recipes.
![image](https://user-images.githubusercontent.com/31905330/85960516-529cbc00-b9a4-11ea-8bb9-8b38bad42484.png)

after being used in a recipe like this:
![image](https://user-images.githubusercontent.com/31905330/85960535-7b24b600-b9a4-11ea-958a-9783c252d390.png)

they receive the NBT they seem to be missing to work in filler.
![image](https://user-images.githubusercontent.com/31905330/85960377-6136a380-b9a3-11ea-9fca-02f3cd353e7e.png)
![2020-06-29_00 09 00](https://user-images.githubusercontent.com/31905330/85960628-46fdc500-b9a5-11ea-8232-4c07713ab118.png)

But also resulting in the autocraft failing:
![image](https://user-images.githubusercontent.com/31905330/85960437-b1156a80-b9a3-11ea-9591-706f78356bd8.png)

Freshly crafted volumetric flasks miss the nbt they need to be used in a Filler.
Tested with just volumetric in SP and they craft with NBT, so it might be an Interactions pack recipe issue.

**Comment by Saereth** [comment]
This was actually a recipe issue with the modpack, this issue could be closed
