### ISSUE TITLE
ME接口终端中不显示本模组的Volumetric Interface.

### ISSUE THREAD

**Issue by CSOLYOO** [exzhawk/VolumetricFlask#14]
![image](https://user-images.githubusercontent.com/20432375/91488019-44eeae80-e8e1-11ea-8fde-9e9b825d2d4d.png)
![image](https://user-images.githubusercontent.com/20432375/91488104-5f288c80-e8e1-11ea-8ad0-64b4a738c0bd.png)

版本 0.18
AE2 版本 appliedenergistics2-rv6-stable-7
使用FTBI 2.0.6

**Comment by balthild** [comment]
As they said in phantamanta44/Lazy-AE2#20, ME interface is hardcoded into the terminal. The only solution is creating an "Volumetric Interface Terminal".
