### ISSUE TITLE
熔融炉功能

### ISSUE THREAD

**Issue by LasmGratel** [exzhawk/VolumetricFlask#3]
![image](https://user-images.githubusercontent.com/6669365/75408588-29661380-5951-11ea-9074-121317904144.png)
如果一个 Volumetric Interface 对着熔融炉/接受物品输入并输出液体的机器,可以接受这种 Flask + 物品 = 装满液体的 Flask 的合成
这个合成要把 Filler 的覆盖掉(或者设置一个优先级?)

**Comment by exzhawk** [comment]
interface的优先级是可以设置的, 默认是0
0.13 版开始, filler 的优先级变为 -1, 低于interface的默认优先级

see https://github.com/exzhawk/VolumetricFlask/issues/2#issuecomment-592100417 for more info

**Comment by exzhawk** [comment]
proposal
如果interface发现有个合成表输入里有空瓶子, 输出里有塞满了红石液体的同样容量的瓶子, 那就先把空瓶子收自己缓存里
然后什么时候来了红石液体, 如果缓存里还有空瓶子, 就先把空瓶子装了塞me

**Comment by LasmGratel** [comment]
Yes yes yes

________________________________

**Comment by LasmGratel** [comment]
Seems working as expected
