### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by almightyju** [exzhawk/VolumetricFlask#5]
So I've been using this mod a lot in a new build since it's so good, but I'm starting to get lag spikes between 2-4000ms in time. I've profiled it using spark and it's at https://spark.lucko.me/#RpmF77Jtc9

In case the link should die this is a screenshot of the profiler section (the provideCrafting function is in 3 separate calls in the full profiling output):
![](https://i.imgur.com/WiJ8IYM.png)

It seems like this function is triggering a lot and taking multiple seconds on a single tick update

https://github.com/exzhawk/VolumetricFlask/blob/6a3b9969a96b31ee1547a24a5326138f126e4507/src/main/java/me/exz/volumetricflask/common/tile/TileFiller.java#L67

Is there anything that can be done? it only seems to have gotten worse as I'm adding more and more fluids :(

**Comment by exzhawk** [comment]
Could you try out a test version?
[VolumetricFlask.zip](https://github.com/exzhawk/VolumetricFlask/files/4489239/VolumetricFlask.zip)
Extract `volumetricflask-0.15.jar` and replace the existed file in your mods folder. This file is same as artifacts at https://github.com/exzhawk/VolumetricFlask/actions/runs/80088913
Don't forget to backup the world save before trying the test version.

I added about 300 fluids to ME network in my local world, add spotted the mentioned function. But the profile result isn't as obvious as yours. The test version seems to be working better.

If lag still occurs often, please profile again and post the result. A world save (with malfunctional machines) and the modpack you use might be helpful.

**Comment by almightyju** [comment]
That is so much better, noticeably less lag, probably didn't help that I had 2 fillers on my network, oops!  

Thank you for fixing that so quickly :)

**Comment by exzhawk** [comment]
Released version 0.16
