### ISSUE TITLE
Autocrafting stuck with fluid input and output

### ISSUE THREAD

**Issue by Theoooooo** [exzhawk/VolumetricFlask#6]
I was testing this mob because it looks very promising at autocrafting items and fluids, but i'm stuck in a issue :

In this exemple, i tried to autocraft methane out of another fluid :
![image](https://user-images.githubusercontent.com/33425208/82131309-29e5ac00-97d4-11ea-903d-f327a6810bf5.png)
1 Carbon Dust
4000 mb Hydrogen

Which result into 5000 mb of Methane

I encoded this recipe :
![image](https://user-images.githubusercontent.com/33425208/82131317-45e94d80-97d4-11ea-8bb4-38ece2c89b72.png)
1 Carbon Dust
Flask of 4000 mb of Hydrogen
One empty flask of 1000 mb
One empty flask of 4000 mb

But the craft seems stuck everytime you add an empty flask with filled flask as items to send to the interface.
If i removed the emply flasks, the items and fluids get pushed correctly to the interface but then output fluid does not get craft into flash, because they are not present into the internal buffer of the interface.

Is it a bug or i am doing it wrong ?

To trick this, i have to output the fluid content to a Tank from EnderIO, export empty 1000 mb flasks inside and export the filled flask after that :
![image](https://user-images.githubusercontent.com/33425208/82131657-cb223180-97d7-11ea-9e84-2ad0c4ea565d.png)
And then encode the recipe this way :
![image](https://user-images.githubusercontent.com/33425208/82131663-d9704d80-97d7-11ea-86dd-fcac04ea5be7.png)

**Comment by exzhawk** [comment]
Should be fixed in version 0.16. Use the recipe with empty volumetric flasks.

**Comment by Theoooooo** [comment]
Awesome ! 
I will test this when i got some spare time

**Comment by Theoooooo** [comment]
@exzhawk Working perfectly !
Thanks

![image](https://user-images.githubusercontent.com/33425208/83321707-b6bb4b80-a251-11ea-9a6c-e7348c0315cf.png)
Output = 5 x 1000mb flask
