### ISSUE TITLE
Prevent craft stuck if not enough fluid quantity

### ISSUE THREAD

**Issue by programgames** [exzhawk/VolumetricFlask#9]
Hello,
When I have 500mb of UU-Matter in my network and I ask a 1000mb volumetric flask, the craft if stuck.

It should be good if the craft detect my 20mb uu-matter craft ( in the mixer from gregtech ce )  and craft the rest ( 25 * 20mb ) , so it could fill the flask and not stuck.

**Comment by programgames** [comment]
Or maybe I have to make a 1000mb volumetric flask of this liquid with 50* 20mb volumetric flask of the same liquid, where 20mb flask

**Comment by exzhawk** [comment]
If you are using the trick (actual recipe: 20mB UU->1 item A, pattern: 1000mB UU -> 50 item A), try reduce multiplier. e.g. use pattern: 100mB UU -> 5 item A instead. However, if you only have 80mB UU, it will be stuck. The ME network has no clue to know it's a 20mB recipe. This is a known limitation and won't get a fix.

**Comment by programgames** [comment]
ok ty
